# Generated by Django 5.2.5 on 2025-08-25 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_customuser_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acudienteprofile',
            name='school',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='school',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='school',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='school',
        ),
    ]
